export const CODIGO_PERSONA_AMBITO = {
  INTERNO_NATURAL: 'TPA001',
  EXTERNO_NATURAL: 'TPA002',
  EXTERNO_JURIDICO: 'TPA003',
  EXTERNO_NATURAL_JURIDICO: 'TPA004'
};

export const TIPO_FIRMA = {
  MANUAL: 1,
  DIGITAL: 2
};
